train: ../datasets/overhead_person/train/images
val: ../datasets/overhead_person/valid/images
test: ../datasets/overhead_person/test/images

nc: 1
names: ['person']

roboflow:
  workspace: riccardo-kxtut
  project: overhead-person-szky0
  version: 3
  license: CC BY 4.0
  url: https://universe.roboflow.com/riccardo-kxtut/overhead-person-szky0/dataset/3